# Generated by Django 4.2 on 2025-04-05 10:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('layout', '0004_box_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='color',
            field=models.CharField(default='#FF0000', max_length=7, verbose_name='box color'),
        ),
        migrations.AlterField(
            model_name='box',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='owner'),
        ),
    ]
